/**
 * Phase D5 — Bidirectional Zod ↔ OpenAPI cross-checks.
 *
 * Source of truth pair (the kill switch against incident-11e9230-class drift):
 *   - Zod side:        landing's runtime validator at `@/lib/cmsSchemas`
 *   - Generated side:  the OpenAPI-derived types at `@/lib/cms-generated`
 *                      (auto-generated by `bun run generate:cms-types`)
 *
 * Compile-time only. Nothing in this file runs at runtime. Vitest's
 * typecheck mode (configured in vitest.config.ts) invokes tsc against
 * the .test-d.ts files; an `expectTypeOf` mismatch surfaces as a normal
 * TypeScript error during `bun run test`.
 *
 * Why bidirectional?
 *   - Forward  (Zod → OpenAPI):  catches landing's Zod being STRICTER than
 *     the backend contract (e.g. landing requires a field that the
 *     backend marks optional) — runtime crash potential when backend
 *     omits the field.
 *   - Backward (OpenAPI → Zod):  catches landing's Zod being LOOSER than
 *     the backend contract (e.g. backend guarantees non-null but
 *     landing's Zod marks it `.nullable()`) — silent contract drift,
 *     exactly the incident-11e9230 failure mode.
 *   Both directions must pass for the contract to be structurally sound.
 *
 * Failure shape (when a check fails) — TypeScript identifies:
 *   - the exact property path of the mismatch,
 *   - the type quote (e.g. `Type 'string | null' is not assignable to
 *     type 'string'`),
 *   - which direction failed (Zod-side vs generated-side) — readable
 *     from the named `it()` block that surfaces the error.
 *
 * D5 rollout order (per playbook):
 *   D5.1 (this file): FAQ pilot.
 *   D5.2:             heightened-watch surfaces (blog list/detail,
 *                     marquee, jobs list/detail) — alt_text non-null
 *                     contract.
 *   D5.3:             remaining flat-content endpoints
 *                     (testimonials, contact-locations, integrations,
 *                     translations).
 *   D5.4:             incident-11e9230 replay — deliberately re-introduce
 *                     `alt_text: z.string().nullable()` on a sacrificial
 *                     branch, prove this gate fails BEFORE the
 *                     consumer typecheck would.
 */

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

import {
  blogListResponseSchema,
  blogPostResponseSchema,
  contactLocationsResponseSchema,
  faqsResponseSchema,
  integrationsResponseSchema,
  jobResponseSchema,
  jobsResponseSchema,
  marqueeImagesResponseSchema,
  testimonialsResponseSchema,
  translationsResponseSchema,
} from "@/lib/cmsSchemas";
import type { paths } from "@/lib/cms-generated";

// Named aliases so the type quote in any failure message clearly
// labels which side is which.
type FaqsResponseFromZod = z.infer<typeof faqsResponseSchema>;
type FaqsResponseFromOpenApi =
  paths["/api/v1/faqs"]["get"]["responses"]["200"]["content"]["application/json"];

describe("D5.1 — /api/v1/faqs Zod ↔ OpenAPI cross-check", () => {
  it("forward — source: Zod, target: OpenAPI-generated (Zod is not stricter than contract)", () => {
    expectTypeOf<FaqsResponseFromZod>().toExtend<FaqsResponseFromOpenApi>();
  });

  it("backward — source: OpenAPI-generated, target: Zod (Zod is not looser than contract)", () => {
    expectTypeOf<FaqsResponseFromOpenApi>().toExtend<FaqsResponseFromZod>();
  });
});

// ════════════════════════════════════════════════════════════════════════
// D5.2 — Heightened-watch surfaces
// ════════════════════════════════════════════════════════════════════════
// These endpoints share the regression class that produced incident
// 11e9230: nullable-vs-non-null mismatches on identifier-like string
// fields. The bidirectional check fails asymmetrically in EITHER
// direction the moment Zod and OpenAPI diverge on:
//   - blog_slides[].alt_text   (DB: TEXT NOT NULL — must NOT be nullable)
//   - marquee_images[].alt_text (DB: TEXT NOT NULL — must NOT be nullable)
//   - job.responsibilities / requirements / benefits / bonuses
//     (parsed JSON columns, handler fallback `?? {}` / `?? []` so the
//     wire shape is ALWAYS materialized — must NOT be nullable)
// D5.4 will deliberately re-introduce one of these as a regression test.

type BlogListResponseFromZod = z.infer<typeof blogListResponseSchema>;
type BlogListResponseFromOpenApi =
  paths["/api/v1/blog"]["get"]["responses"]["200"]["content"]["application/json"];

describe("D5.2 — /api/v1/blog Zod ↔ OpenAPI cross-check (list)", () => {
  it("forward — source: Zod, target: OpenAPI-generated (Zod is not stricter than contract)", () => {
    expectTypeOf<BlogListResponseFromZod>().toExtend<BlogListResponseFromOpenApi>();
  });

  it("backward — source: OpenAPI-generated, target: Zod (Zod is not looser than contract)", () => {
    expectTypeOf<BlogListResponseFromOpenApi>().toExtend<BlogListResponseFromZod>();
  });
});

type BlogPostResponseFromZod = z.infer<typeof blogPostResponseSchema>;
type BlogPostResponseFromOpenApi =
  paths["/api/v1/blog/{slug}"]["get"]["responses"]["200"]["content"]["application/json"];

describe("D5.2 — /api/v1/blog/{slug} Zod ↔ OpenAPI cross-check (detail, heightened-watch: slides[].alt_text non-null)", () => {
  it("forward — source: Zod, target: OpenAPI-generated (Zod is not stricter than contract)", () => {
    expectTypeOf<BlogPostResponseFromZod>().toExtend<BlogPostResponseFromOpenApi>();
  });

  it("backward — source: OpenAPI-generated, target: Zod (Zod is not looser than contract — would catch alt_text nullable regression)", () => {
    expectTypeOf<BlogPostResponseFromOpenApi>().toExtend<BlogPostResponseFromZod>();
  });
});

type MarqueeImagesResponseFromZod = z.infer<typeof marqueeImagesResponseSchema>;
type MarqueeImagesResponseFromOpenApi =
  paths["/api/v1/marquee-images"]["get"]["responses"]["200"]["content"]["application/json"];

describe("D5.2 — /api/v1/marquee-images Zod ↔ OpenAPI cross-check (heightened-watch: alt_text non-null)", () => {
  it("forward — source: Zod, target: OpenAPI-generated (Zod is not stricter than contract)", () => {
    expectTypeOf<MarqueeImagesResponseFromZod>().toExtend<MarqueeImagesResponseFromOpenApi>();
  });

  it("backward — source: OpenAPI-generated, target: Zod (Zod is not looser than contract — would catch alt_text nullable regression)", () => {
    expectTypeOf<MarqueeImagesResponseFromOpenApi>().toExtend<MarqueeImagesResponseFromZod>();
  });
});

type JobsResponseFromZod = z.infer<typeof jobsResponseSchema>;
type JobsResponseFromOpenApi =
  paths["/api/v1/jobs"]["get"]["responses"]["200"]["content"]["application/json"];

describe("D5.2 — /api/v1/jobs Zod ↔ OpenAPI cross-check (list)", () => {
  it("forward — source: Zod, target: OpenAPI-generated (Zod is not stricter than contract)", () => {
    expectTypeOf<JobsResponseFromZod>().toExtend<JobsResponseFromOpenApi>();
  });

  it("backward — source: OpenAPI-generated, target: Zod (Zod is not looser than contract)", () => {
    expectTypeOf<JobsResponseFromOpenApi>().toExtend<JobsResponseFromZod>();
  });
});

type JobResponseFromZod = z.infer<typeof jobResponseSchema>;
type JobResponseFromOpenApi =
  paths["/api/v1/jobs/{slug}"]["get"]["responses"]["200"]["content"]["application/json"];

describe("D5.2 — /api/v1/jobs/{slug} Zod ↔ OpenAPI cross-check (detail, JSON-string fields materialized to wire shape)", () => {
  it("forward — source: Zod, target: OpenAPI-generated (Zod is not stricter than contract)", () => {
    expectTypeOf<JobResponseFromZod>().toExtend<JobResponseFromOpenApi>();
  });

  it("backward — source: OpenAPI-generated, target: Zod (Zod is not looser than contract — covers responsibilities/requirements/benefits/bonuses always-present invariant)", () => {
    expectTypeOf<JobResponseFromOpenApi>().toExtend<JobResponseFromZod>();
  });
});

// ════════════════════════════════════════════════════════════════════════
// D5.3 — Remaining flat-content endpoints
// ════════════════════════════════════════════════════════════════════════
// MED-risk surfaces (no alt_text class). Covers the last 4 annotated
// endpoints so the full 10-endpoint OpenAPI surface is bidirectionally
// type-checked. After this, EVERY annotated CMS response shape is gated.

type TestimonialsResponseFromZod = z.infer<typeof testimonialsResponseSchema>;
type TestimonialsResponseFromOpenApi =
  paths["/api/v1/testimonials"]["get"]["responses"]["200"]["content"]["application/json"];

describe("D5.3 — /api/v1/testimonials Zod ↔ OpenAPI cross-check", () => {
  it("forward — source: Zod, target: OpenAPI-generated (Zod is not stricter than contract)", () => {
    expectTypeOf<TestimonialsResponseFromZod>().toExtend<TestimonialsResponseFromOpenApi>();
  });

  it("backward — source: OpenAPI-generated, target: Zod (Zod is not looser than contract)", () => {
    expectTypeOf<TestimonialsResponseFromOpenApi>().toExtend<TestimonialsResponseFromZod>();
  });
});

type ContactLocationsResponseFromZod = z.infer<typeof contactLocationsResponseSchema>;
type ContactLocationsResponseFromOpenApi =
  paths["/api/v1/contact-locations"]["get"]["responses"]["200"]["content"]["application/json"];

describe("D5.3 — /api/v1/contact-locations Zod ↔ OpenAPI cross-check", () => {
  it("forward — source: Zod, target: OpenAPI-generated (Zod is not stricter than contract)", () => {
    expectTypeOf<ContactLocationsResponseFromZod>().toExtend<ContactLocationsResponseFromOpenApi>();
  });

  it("backward — source: OpenAPI-generated, target: Zod (Zod is not looser than contract)", () => {
    expectTypeOf<ContactLocationsResponseFromOpenApi>().toExtend<ContactLocationsResponseFromZod>();
  });
});

type IntegrationsResponseFromZod = z.infer<typeof integrationsResponseSchema>;
type IntegrationsResponseFromOpenApi =
  paths["/api/v1/integrations"]["get"]["responses"]["200"]["content"]["application/json"];

describe("D5.3 — /api/v1/integrations Zod ↔ OpenAPI cross-check", () => {
  it("forward — source: Zod, target: OpenAPI-generated (Zod is not stricter than contract)", () => {
    expectTypeOf<IntegrationsResponseFromZod>().toExtend<IntegrationsResponseFromOpenApi>();
  });

  it("backward — source: OpenAPI-generated, target: Zod (Zod is not looser than contract)", () => {
    expectTypeOf<IntegrationsResponseFromOpenApi>().toExtend<IntegrationsResponseFromZod>();
  });
});

type TranslationsResponseFromZod = z.infer<typeof translationsResponseSchema>;
type TranslationsResponseFromOpenApi =
  paths["/api/v1/translations"]["get"]["responses"]["200"]["content"]["application/json"];

describe("D5.3 — /api/v1/translations Zod ↔ OpenAPI cross-check", () => {
  it("forward — source: Zod, target: OpenAPI-generated (Zod is not stricter than contract)", () => {
    expectTypeOf<TranslationsResponseFromZod>().toExtend<TranslationsResponseFromOpenApi>();
  });

  it("backward — source: OpenAPI-generated, target: Zod (Zod is not looser than contract)", () => {
    expectTypeOf<TranslationsResponseFromOpenApi>().toExtend<TranslationsResponseFromZod>();
  });
});
