/**
 * Phase D5 — Bidirectional Zod ↔ OpenAPI cross-checks.
 *
 * Source of truth pair (the kill switch against incident-11e9230-class drift):
 *   - Zod side:        landing's runtime validator at `@/lib/cmsSchemas`
 *   - Generated side:  the OpenAPI-derived types at `@/lib/cms-generated`
 *                      (auto-generated by `bun run generate:cms-types`)
 *
 * Compile-time only. Nothing in this file runs at runtime. Vitest's
 * typecheck mode (configured in vitest.config.ts) invokes tsc against
 * the .test-d.ts files; an `expectTypeOf` mismatch surfaces as a normal
 * TypeScript error during `bun run test`.
 *
 * Why bidirectional?
 *   - Forward  (Zod → OpenAPI):  catches landing's Zod being STRICTER than
 *     the backend contract (e.g. landing requires a field that the
 *     backend marks optional) — runtime crash potential when backend
 *     omits the field.
 *   - Backward (OpenAPI → Zod):  catches landing's Zod being LOOSER than
 *     the backend contract (e.g. backend guarantees non-null but
 *     landing's Zod marks it `.nullable()`) — silent contract drift,
 *     exactly the incident-11e9230 failure mode.
 *   Both directions must pass for the contract to be structurally sound.
 *
 * Failure shape (when a check fails) — TypeScript identifies:
 *   - the exact property path of the mismatch,
 *   - the type quote (e.g. `Type 'string | null' is not assignable to
 *     type 'string'`),
 *   - which direction failed (Zod-side vs generated-side) — readable
 *     from the named `it()` block that surfaces the error.
 *
 * D5 rollout order (per playbook):
 *   D5.1 (this file): FAQ pilot.
 *   D5.2:             heightened-watch surfaces (blog list/detail,
 *                     marquee, jobs list/detail) — alt_text non-null
 *                     contract.
 *   D5.3:             remaining flat-content endpoints
 *                     (testimonials, contact-locations, integrations,
 *                     translations).
 *   D5.4:             incident-11e9230 replay — deliberately re-introduce
 *                     `alt_text: z.string().nullable()` on a sacrificial
 *                     branch, prove this gate fails BEFORE the
 *                     consumer typecheck would.
 */

import { describe, it, expectTypeOf } from "vitest";
import type { z } from "zod";

import { faqsResponseSchema } from "@/lib/cmsSchemas";
import type { paths } from "@/lib/cms-generated";

// Named aliases so the type quote in any failure message clearly
// labels which side is which.
type FaqsResponseFromZod = z.infer<typeof faqsResponseSchema>;
type FaqsResponseFromOpenApi =
  paths["/api/v1/faqs"]["get"]["responses"]["200"]["content"]["application/json"];

describe("D5.1 — /api/v1/faqs Zod ↔ OpenAPI cross-check", () => {
  it("forward — source: Zod, target: OpenAPI-generated (Zod is not stricter than contract)", () => {
    expectTypeOf<FaqsResponseFromZod>().toMatchTypeOf<FaqsResponseFromOpenApi>();
  });

  it("backward — source: OpenAPI-generated, target: Zod (Zod is not looser than contract)", () => {
    expectTypeOf<FaqsResponseFromOpenApi>().toMatchTypeOf<FaqsResponseFromZod>();
  });
});
