import { useState } from "react";

type Channel = "sea" | "air" | "express";
type RateRow = [string, string, string, string, string, string];

const breaks = ["12KG+", "21KG+", "51KG+", "100KG+"];
const seaRows = (values: string[][]): RateRow[] => values.map(([region, zip, ...rates]) => [region, zip, ...rates] as RateRow);

const cards = [
    { channel: "sea" as Channel, title: "🚢 SEA Matson CLX — General & Battery Cargo", subtitle: "Fastest sea lane · Vessel departs every Wednesday", transit: "20–25 business days", sensitive: "✓ Sensitive OK", rows: seaRows([["West US", "89", "$3.45", "$3.08", "$2.89", "$2.52"], ["Central US", "4, 5, 6, 7", "$3.64", "$3.26", "$3.08", "$2.71"], ["East US", "0, 1, 2, 3", "$3.82", "$3.45", "$3.26", "$2.89"]]), rules: "Ocean transit 13–17 calendar days · min 12kg · max 22kg/carton · residential +$4.50/carton · remote +$6.50/carton · duty & customs included." },
    { channel: "sea" as Channel, title: "🚢 SEA Matson MAX — Sensitive Cargo", subtitle: "Battery, liquid, sensitive electronics · Dedicated sensitive cargo lane", transit: "25 business days", sensitive: "✓ Sensitive cargo", rows: seaRows([["West US", "89", "$5.41", "$4.85", "$4.66", "$4.10"], ["Central US", "4, 5, 6, 7", "$5.60", "$5.04", "$4.85", "$4.29"], ["East US", "0, 1, 2, 3", "$5.78", "$5.22", "$5.04", "$4.48"]]), rules: "Ocean transit 14–18 calendar days · all sensitive goods accepted · min 12kg · max 22kg/carton · duty & customs included." },
    { channel: "sea" as Channel, title: "🚢 SEA ZIM — General & Battery Cargo", subtitle: "Competitive rates · General cargo and battery", transit: "25–30 business days", sensitive: "✓ Battery OK", rows: seaRows([["West US", "89", "$3.08", "$2.71", "$2.89", "$2.33"], ["Central US", "4, 5, 6, 7", "$3.26", "$2.89", "$3.08", "$2.52"], ["East US", "0, 1, 2, 3", "$3.45", "$3.08", "$3.26", "$2.71"]]), rules: "Ocean transit 16–19 calendar days · min 12kg · max 22kg/carton · duty & customs included." },
    { channel: "sea" as Channel, title: "🚢 SEA Yantian — General & Battery Cargo", subtitle: "Most economical rate · General cargo only", transit: "30–35 business days", sensitive: "✗ No sensitive", rows: seaRows([["West US", "89", "$2.99", "$2.61", "$2.43", "$2.11"], ["Central US", "4, 5, 6, 7", "$3.17", "$2.80", "$2.61", "$2.29"], ["East US", "0, 1, 2, 3", "$3.36", "$2.99", "$2.80", "$2.48"]]), rules: "Ocean transit 18–25 calendar days · general & battery cargo · min 12kg · max 22kg/carton · duty & customs included." },
    { channel: "air" as Channel, title: "✈️ UPS Air — Fast", subtitle: "General cargo · Fast lane", transit: "7–10 business days", sensitive: "✓ Sensitive OK", rows: seaRows([["West US", "89", "$12.70", "$12.20", "$11.60", "$10.90"], ["Central US", "4, 5, 6, 7", "$12.90", "$12.40", "$11.80", "$11.10"], ["East US", "0, 1, 2, 3", "$12.90", "$12.40", "$11.80", "$11.10"]]), rules: "Pickup in US 4–6 business days · last-mile UPS · min 12kg · max 22kg/carton · duty & customs included." },
    { channel: "air" as Channel, title: "✈️ UPS Air — Standard", subtitle: "General cargo · Standard lane", transit: "8–13 business days", sensitive: "✓ Sensitive OK", rows: seaRows([["West US", "89", "$12.20", "$11.60", "$11.20", "$10.70"], ["Central US", "4, 5, 6, 7", "$12.40", "$11.80", "$11.40", "$10.90"], ["East US", "0, 1, 2, 3", "$12.40", "$11.80", "$11.40", "$10.90"]]), rules: "Pickup in US 6–8 business days · last-mile UPS · min 12kg · max 22kg/carton · duty & customs included." },
    { channel: "air" as Channel, title: "✈️ UPS Air — Battery & Magnetic Cargo", subtitle: "Sensitive cargo · Battery / magnetic", transit: "8–13 business days", sensitive: "✓ Sensitive", rows: seaRows([["West US", "89", "$12.50", "$12.00", "$11.40", "$10.70"], ["Central US", "4, 5, 6, 7", "$12.70", "$12.20", "$11.80", "$10.90"], ["East US", "0, 1, 2, 3", "$12.70", "$12.20", "$11.60", "$10.90"]]), rules: "Pickup in US 7–9 business days · last-mile UPS · min 12kg · max 22kg/carton · duty & customs included." },
    { channel: "air" as Channel, title: "✈️ UPS Air — Liquid Cargo", subtitle: "Sensitive cargo · Liquid goods", transit: "8–13 business days", sensitive: "✓ Sensitive", rows: seaRows([["West US", "89", "$12.90", "$12.40", "$12.00", "$11.60"], ["Central US", "4, 5, 6, 7", "$12.70", "$12.20", "$11.80", "$11.40"], ["East US", "0, 1, 2, 3", "$12.90", "$12.40", "$12.00", "$11.60"]]), rules: "Pickup in US 6–8 business days · last-mile UPS · min 12kg · max 22kg/carton · duty & customs included." },
    { channel: "express" as Channel, title: "📦 Express FedEx — Hong Kong", subtitle: "From 31kg+ · Sensitive cargo accepted · V/5000", transit: "7–10 business days", sensitive: "✓ Duty incl. · consignee assists if inspected", rows: [["Shipping rate", "31kg+", "$11.00/kg", "", "", ""], ["Handling fee", "Per shipment", "$28.00/shipment", "", "", ""]], rules: "Express from Hong Kong · remote fee included · max 22kg/carton · THG files standard import." },
    { channel: "express" as Channel, title: "📦 Express UPS — Hong Kong", subtitle: "From 31kg+ · Sensitive cargo accepted · V/5000", transit: "5–7 business days", sensitive: "✓ Duty incl. · consignee assists if inspected", rows: [["Shipping rate", "31kg+", "$11.80/kg", "", "", ""], ["Handling fee", "Per shipment", "$28.00/shipment", "", "", ""]], rules: "Express from Hong Kong · remote fee included · max 22kg/carton · THG files standard import." },
    { channel: "express" as Channel, title: "📦 Express DHL — Hong Kong", subtitle: "From 21kg+ · Sensitive cargo accepted · V/5000", transit: "3–5 business days", sensitive: "Duty & customs NOT included", rows: [["General cargo", "21kg+", "$13.50/kg", "", "", ""], ["Sensitive cargo", "21kg+", "$14.70/kg", "", "", ""]], rules: "Express from Hong Kong · duty/customs not included · remote fee included · max 22kg/carton." },
] as const;

const compare = cards.map((card) => ({ channel: card.title, type: card.channel === "sea" ? "Sea" : card.channel === "air" ? "Air" : "Express", transit: card.transit, cutoff: card.channel === "sea" ? "Sat 12:00" : "Daily 12:00", rate: card.channel === "express" ? card.rows[0][2] : card.rows[0][3], duty: card.channel === "express" && card.title.includes("DHL") ? "Not included" : "Included", sensitive: card.sensitive }));

function RateCard({ card }: { card: typeof cards[number] }) {
    const [open, setOpen] = useState(card.title.includes("Matson CLX"));
    const isExpress = card.channel === "express";
    return <article className={`rounded-xl border overflow-hidden bg-white shadow-sm ${card.channel === "sea" ? "border-blue-100" : card.channel === "air" ? "border-green-100" : "border-orange-100"}`}>
        <button type="button" onClick={() => setOpen((value) => !value)} className="w-full flex flex-wrap items-center gap-3 px-4 py-4 text-left hover:bg-slate-50">
            <span className="flex-1 min-w-[240px]"><strong className="block text-sm text-slate-900">{card.title}</strong><span className="text-xs text-slate-500">{card.subtitle}</span></span>
            <span className="text-[11px] rounded-full bg-emerald-100 text-emerald-700 px-2.5 py-1">{card.sensitive}</span><span className="text-[11px] rounded-full bg-blue-100 text-blue-700 px-2.5 py-1">🕒 {card.transit}</span><span aria-hidden className="text-slate-400">{open ? "▼" : "▶"}</span>
        </button>
        {open && <div className="border-t border-slate-100"><div className="overflow-x-auto p-4"><table className="w-full text-xs"><thead><tr className="bg-slate-50 text-slate-500">{(isExpress ? ["Hạng mục", "Condition", "Đơn giá"] : ["Region", "ZIP Prefix", ...breaks]).map((head) => <th key={head} className="px-3 py-2 text-left whitespace-nowrap">{head}</th>)}</tr></thead><tbody>{card.rows.map((row, index) => <tr key={`${row[0]}-${index}`} className="border-t border-slate-100"><td className="px-3 py-2 font-medium">{row[0]}</td><td className="px-3 py-2 text-slate-500">{row[1]}</td>{(isExpress ? [row[2]] : row.slice(2)).map((value, cell) => <td key={`${cell}-${value}`} className="px-3 py-2 font-mono text-blue-700 whitespace-nowrap">{value || "—"}</td>)}</tr>)}</tbody></table></div><p className="bg-slate-50 px-4 py-3 text-xs leading-relaxed text-slate-600">📋 {card.rules}</p></div>}
    </article>;
}

export default function CnUsRateCard() {
    return <div className="space-y-8">
        <section className="rounded-xl border border-slate-200 bg-white overflow-hidden shadow-sm"><div className="px-4 py-4 border-b border-slate-100"><h2 className="font-bold text-slate-900">⚡ Quick Comparison — All Shipping Channels</h2><p className="text-xs text-slate-500 mt-1">Rate from 21KG+ · West US (ZIP 89) · General cargo</p></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="bg-slate-50 text-slate-500">{["Channel", "Type", "Transit", "Cut-off", "Rate from", "Duty & Customs", "Sensitive"].map((head) => <th key={head} className="px-3 py-2 text-left whitespace-nowrap">{head}</th>)}</tr></thead><tbody>{compare.map((row) => <tr key={row.channel} className="border-t border-slate-100"><td className="px-3 py-2 font-semibold whitespace-nowrap">{row.channel}</td><td className="px-3 py-2">{row.type}</td><td className="px-3 py-2 font-mono whitespace-nowrap">{row.transit}</td><td className="px-3 py-2 font-mono whitespace-nowrap">{row.cutoff}</td><td className="px-3 py-2 font-mono text-blue-700 whitespace-nowrap">{row.rate}</td><td className="px-3 py-2 whitespace-nowrap">{row.duty}</td><td className="px-3 py-2 whitespace-nowrap">{row.sensitive}</td></tr>)}</tbody></table></div></section>
        <aside className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>⚠️ Notes</strong><div className="mt-2 grid gap-2 sm:grid-cols-2"><span>Sea cut-off: Saturday 12:00 — vessel departs following Wednesday.</span><span>Air & Express cut-off: Daily 12:00 (except Sunday).</span><span>Toys & Games: +$0.38/kg · Sea & Air only.</span><span>Bags & Textiles: +$0.19/kg · Sea & Air only.</span><span>Residential delivery: +$4.50/carton · Sea & Air only.</span><span>Remote Area Fee: $6.50/carton.</span><span>Sea & Air: V/6000.</span><span>Express: V/5000.</span></div></aside>
        {["sea", "air", "express"].map((channel) => <section key={channel}><div className="mb-3 border-b-2 border-slate-200 pb-3"><h2 className="text-xl font-black text-slate-900">{channel === "sea" ? "🚢 Sea Freight" : channel === "air" ? "✈️ Air Freight (UPS)" : "📦 Express — Hong Kong Hub"}</h2><p className="text-xs text-slate-500">{channel === "sea" ? "Matson CLX · Matson MAX · ZIM · Yantian · duty & customs included" : channel === "air" ? "UPS Air · duty & customs included · daily cut-off" : "FedEx · UPS · DHL via HKG · review duty/customs per line"}</p></div><div className="space-y-3">{cards.filter((card) => card.channel === channel).map((card) => <RateCard key={card.title} card={card} />)}</div></section>)}
        <p className="border-t border-slate-200 pt-4 text-center text-xs leading-relaxed text-slate-500"><strong>CN → US Rate Card · THG Fulfill</strong><br />Rates exclude cargo-type surcharges. Unit: USD/kg. Sea & Air: V/6000 · Express: V/5000.<br />Contact THG for a precise quote based on the specific shipment.</p>
    </div>;
}
