// One-shot script: read landing's static i18n dictionary and emit SQL
// that seeds the CMS `translations` D1 table with every (key, locale, value)
// triple. Output is consumed as a wrangler migration in cmsthgfulfill.
//
// Run from landing repo root:
//   bun run scripts/export-i18n-sql.ts > ../cmsthgfulfill/db/migrations/0022_seed_translations.sql
//
// Idempotent: uses INSERT OR IGNORE so re-applying does not clobber any
// edits operator has already made through /admin/content/translations.

import { translations } from "../src/lib/i18n";

const HEADER = `-- 0022: bulk-seed D1 \`translations\` from landing's static i18n.tsx dictionary.
--
-- Generated by THG_landingpage/scripts/export-i18n-sql.ts.
-- DO NOT edit by hand — re-run the script to regenerate.
--
-- Idempotent: INSERT OR IGNORE preserves operator edits made via
-- /admin/content/translations. Static i18n.tsx remains the fallback
-- when a row is absent from this table.
`;

function escape(s: string): string {
  // SQLite single-quote escape — double the quote
  return s.replace(/'/g, "''");
}

const lines: string[] = [];
let count = 0;
for (const [key, vals] of Object.entries(translations)) {
  for (const locale of ["en", "vi", "zh"] as const) {
    const value = vals[locale];
    if (typeof value !== "string") continue;
    lines.push(`  ('${escape(key)}', '${locale}', '${escape(value)}')`);
    count += 1;
  }
}

console.log(HEADER);
console.log(`-- Total rows: ${count}`);
console.log(`INSERT OR IGNORE INTO translations (key, locale, value) VALUES`);
console.log(lines.join(",\n") + ";");
